question_list = [{}, #0 left blank
    {'question': 'q1', 'is_blank': False,  'answer': 3, 'blank_answer': '',
                 'option_one_text': 'Option1', 'option_two_text': 'asd', 'option_three_text': 'asd', 'option_four_text': 'asd', 'hint_text':'Click here for hint', 'hint_link':'https://youtu.be/dQw4w9WgXcQ' },
    {'question': 'q2', 'is_blank': True,  'answer': 0, 'blank_answer': 'hello',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q3', 'is_blank': False,  'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q4', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '', 'hint_text':'', 'hint_link':'',},
    {'question': 'q5', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q6', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q7', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q8', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q9', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q10', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q11', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q12', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q13', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q14', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q15', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '', 'hint_text':'', 'hint_link':'',},
    {'question': 'q16', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q17', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '', 'hint_text':'', 'hint_link':'',},
    {'question': 'q18', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '', 'hint_text':'', 'hint_link':'',},
    {'question': 'q19', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
    {'question': 'q20', 'is_blank': False, 'answer': 0, 'blank_answer': '',
                 'option_one_text': '', 'option_two_text': '', 'option_three_text': '', 'option_four_text': '','hint_text':'', 'hint_link':'', },
]