# Generated by Django 3.1.3 on 2021-08-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='Department', max_length=50),
        ),
    ]
