# Generated by Django 3.1.3 on 2021-08-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0002_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='member',
        ),
        migrations.AddField(
            model_name='department',
            name='members',
            field=models.ManyToManyField(related_name='dept_member', to='users.Member'),
        ),
    ]
