# Generated by Django 3.1.3 on 2021-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210810_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('cp', 'Competetive Programming'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development'), ('ui', 'UI/UX')], max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='tech_stack',
            field=models.CharField(max_length=200),
        ),
    ]
