# Generated by Django 3.1.3 on 2021-08-04 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('username', models.CharField(blank=True, default='user', max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.customuser')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('bits_id', models.CharField(max_length=13, unique=True, verbose_name='BITS ID')),
                ('githubid', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Github ID')),
                ('pr1', models.CharField(choices=[('cp', 'Competitive Programing'), ('fe', 'Frontend Web Dvelopment'), ('be', 'Backend Web Dvelopment'), ('ap', 'App Devlpment '), ('ui', 'UI/UX ')], default=None, max_length=2, verbose_name='First Priority')),
                ('pr2', models.CharField(choices=[('cp', 'Competitive Programing'), ('fe', 'Frontend Web Dvelopment'), ('be', 'Backend Web Dvelopment'), ('ap', 'App Devlpment '), ('ui', 'UI/UX ')], default=None, max_length=2, verbose_name='Second Priority')),
                ('pr3', models.CharField(choices=[('cp', 'Competitive Programing'), ('fe', 'Frontend Web Dvelopment'), ('be', 'Backend Web Dvelopment'), ('ap', 'App Devlpment '), ('ui', 'UI/UX ')], default=None, max_length=2, verbose_name='Third Priority')),
                ('pr4', models.CharField(choices=[('cp', 'Competitive Programing'), ('fe', 'Frontend Web Dvelopment'), ('be', 'Backend Web Dvelopment'), ('ap', 'App Devlpment '), ('ui', 'UI/UX ')], default=None, max_length=2, verbose_name='Fourth Priority')),
                ('pr5', models.CharField(choices=[('cp', 'Competitive Programing'), ('fe', 'Frontend Web Dvelopment'), ('be', 'Backend Web Dvelopment'), ('ap', 'App Devlpment '), ('ui', 'UI/UX ')], default=None, max_length=2, verbose_name='Fifth Priority')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.customuser')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('interests', models.TextField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bits_id', models.CharField(max_length=50, verbose_name='BITS ID')),
                ('bits_email', models.EmailField(max_length=100, verbose_name='BITS Email')),
                ('department', models.CharField(choices=[('cp', 'Competetive Programming'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development'), ('ui', 'UI/UX')], max_length=2)),
                ('github', models.CharField(max_length=20)),
                ('linked_in', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
