# Generated by Django 3.2.5 on 2021-12-17 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('username', models.CharField(blank=True, default='user', max_length=255, null=True)),
                ('is_visitor', models.BooleanField(default=False)),
                ('is_candidate', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidate', serialize=False, to='users.customuser')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('bits_id', models.CharField(max_length=13, unique=True, verbose_name='BITS ID')),
                ('bits_email', models.EmailField(default='f20xxxxxx@*.bits-pilani.ac.in', max_length=100, verbose_name='BITS Email')),
                ('github', models.CharField(default='my_github', max_length=20)),
                ('pr1', models.CharField(choices=[('cp', 'Competitive Programing'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development '), ('ui', 'UI/UX'), ('gd', 'Game Development')], default=None, max_length=2, verbose_name='First Priority')),
                ('pr2', models.CharField(choices=[('cp', 'Competitive Programing'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development '), ('ui', 'UI/UX'), ('gd', 'Game Development')], default=None, max_length=2, verbose_name='Second Priority')),
                ('pr3', models.CharField(choices=[('cp', 'Competitive Programing'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development '), ('ui', 'UI/UX'), ('gd', 'Game Development')], default=None, max_length=2, verbose_name='Third Priority')),
                ('pr4', models.CharField(choices=[('cp', 'Competitive Programing'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development '), ('ui', 'UI/UX'), ('gd', 'Game Development')], default=None, max_length=2, verbose_name='Fourth Priority')),
                ('pr5', models.CharField(choices=[('cp', 'Competitive Programing'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development '), ('ui', 'UI/UX'), ('gd', 'Game Development')], default=None, max_length=2, verbose_name='Fifth Priority')),
                ('answer_json', jsonfield.fields.JSONField()),
                ('exam_given', models.BooleanField(default=False)),
                ('exam_attempt_time', models.TextField(default='null')),
                ('exam_given_time', models.TextField(default='null')),
                ('score', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='visitor', serialize=False, to='users.customuser')),
                ('interests', models.TextField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bits_id', models.CharField(default='20XXXXXSXXXX', max_length=50, verbose_name='BITS ID')),
                ('bits_email', models.EmailField(default='f20xxxxxx@*.bits-pilani.ac.in', max_length=100, verbose_name='BITS Email')),
                ('github', models.CharField(default='my_github', max_length=20)),
                ('codeforces_id', models.CharField(blank=True, max_length=30)),
                ('linked_in', models.CharField(blank=True, max_length=20)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='profile_pics')),
                ('summary', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='main.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
