# Generated by Django 3.2.5 on 2021-12-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='bits_email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='bits_email',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bits_id',
            field=models.CharField(default='2021XXXXXXXXP', max_length=13, verbose_name='BITS ID'),
        ),
    ]
