# Generated by Django 3.2.5 on 2022-01-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211230_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pr6',
            field=models.CharField(choices=[('cp', 'Competetive Programming'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development'), ('ui', 'UI/UX'), ('gd', 'Game Development'), ('vi', 'Video Editing')], default=None, max_length=2, verbose_name='Sixth Priority'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pr7',
            field=models.CharField(choices=[('cp', 'Competetive Programming'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development'), ('ui', 'UI/UX'), ('gd', 'Game Development'), ('vi', 'Video Editing')], default=None, max_length=2, verbose_name='Seventh Priority'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pr1',
            field=models.CharField(choices=[('cp', 'Competetive Programming'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development'), ('ui', 'UI/UX'), ('gd', 'Game Development'), ('vi', 'Video Editing')], default=None, max_length=2, verbose_name='First Priority'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pr2',
            field=models.CharField(choices=[('cp', 'Competetive Programming'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development'), ('ui', 'UI/UX'), ('gd', 'Game Development'), ('vi', 'Video Editing')], default=None, max_length=2, verbose_name='Second Priority'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pr3',
            field=models.CharField(choices=[('cp', 'Competetive Programming'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development'), ('ui', 'UI/UX'), ('gd', 'Game Development'), ('vi', 'Video Editing')], default=None, max_length=2, verbose_name='Third Priority'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pr4',
            field=models.CharField(choices=[('cp', 'Competetive Programming'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development'), ('ui', 'UI/UX'), ('gd', 'Game Development'), ('vi', 'Video Editing')], default=None, max_length=2, verbose_name='Fourth Priority'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pr5',
            field=models.CharField(choices=[('cp', 'Competetive Programming'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development'), ('ui', 'UI/UX'), ('gd', 'Game Development'), ('vi', 'Video Editing')], default=None, max_length=2, verbose_name='Fifth Priority'),
        ),
    ]
