# Generated by Django 3.2.5 on 2022-01-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220104_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='github',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
