# Generated by Django 3.2.5 on 2022-01-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_candidate_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pr8',
            field=models.CharField(choices=[('cp', 'Competetive Programming'), ('fe', 'Frontend Web Development'), ('be', 'Backend Web Development'), ('ap', 'App Development'), ('ui', 'UI/UX'), ('gd', 'Game Development'), ('vi', 'Video Editing')], default=None, max_length=2, verbose_name='Eigth Priority'),
        ),
    ]
