# Generated by Django 3.2.5 on 2022-01-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidate_pr8'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
