# Generated by Django 3.2.5 on 2022-01-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220128_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='score',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
