# Generated by Django 3.2.5 on 2021-09-16 09:47


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blank', models.BooleanField()),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('question_file', models.FileField(blank=True, null=True, upload_to='questions/')),
                ('answer', models.IntegerField(blank=True, null=True)),
                ('blank_answer', models.CharField(blank=True, max_length=500, null=True)),
                ('option_one_text', models.CharField(blank=True, max_length=500, null=True)),
                ('option_one_file', models.FileField(blank=True, null=True, upload_to='questions/')),
                ('option_two_text', models.CharField(blank=True, max_length=500, null=True)),
                ('option_two_file', models.FileField(blank=True, null=True, upload_to='questions/')),
                ('option_three_text', models.CharField(blank=True, max_length=500, null=True)),
                ('option_three_file', models.FileField(blank=True, null=True, upload_to='questions/')),
                ('option_four_text', models.CharField(blank=True, max_length=500, null=True)),
                ('option_four_file', models.FileField(blank=True, null=True, upload_to='questions/')),
            ],
        ),
    ]
