# Generated by Django 3.2.5 on 2022-01-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hint_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
